### ISSUE TITLE
有没有出esp8266开源工程的计划呢？

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-qcloud#1]
有没有出esp8266开源工程的计划呢？

**Comment by Eavo** [comment]
暂时还没有，请问下您那边是有什么样的项目需求吗？可以通过 sales@espressif.com 报进来，我们评估后会列入计划。希望我的回答对您有帮助，谢谢。

**Comment by Eavo** [comment]
您好，谢谢您的宝贵建议。我们已将支持 ESP8266 列入 Qcloud SDK 的 feature list 中，当前已在重构阶段，近期将 release，请知悉。
