### ISSUE TITLE
[CLDGIT-2]这个demo怎么都通不过

### ISSUE THREAD

**Issue by zilanghe** [espressif/esp-qcloud#2]
ERR|1970-01-01 00:00:13|HAL_TLS_mbedtls.c|HAL_TLS_Connect(253): mbedtls_ssl_hand
shake failed returned 0x6800
DBG|1970-01-01 00:00:13|HAL_TLS_mbedtls.c|HAL_TLS_Disconnect(277): handle is NUL
L
ERR|1970-01-01 00:00:13|mqtt_client.c|IOT_MQTT_Construct(90): mqtt connect with
id:  failed: -1001
E (13548) esp32-qcloud-mqtt-demo: Cloud Device Construct Failed

idf版本为3.0.7

**Comment by xiewenxiang** [comment]
@zilanghe 
感谢你的信息， 我们会尽快确认这个问题

**Comment by xiewenxiang** [comment]
@zilanghe  看你的log， 应该是key 设置的不对吧，烧录的key 正确吗？

**Comment by zilanghe** [comment]
@xiewenxiang

正确的。烧录同样的固件，多次运行，有时subscribe能成功，多数时候不能；即使subscribe成功，也会返回-111的错误代码。

**Comment by Eavo** [comment]
谢谢您的建议，当前我们计划重构 & 升级 Qcloud SDK，之后将基于新的 SDK 测试这个问题，届时也欢迎您和我们一起测试。

**Comment by jsonsiyuan** [comment]
需要再sdk中开启一些TLS的密钥协商方式

**Comment by jsonsiyuan** [comment]
TLS握手失败 使用的是密钥认证，需要 Enable PSK based ciphersuite modes
