### ISSUE TITLE
反馈几个问题

### ISSUE THREAD

**Issue by jsonsiyuan** [espressif/esp-qcloud#3]
1.这个demo的readme说明有勘误，这是一个没有使用证书认证的demo，而是使用了设备密钥认证的demo。代码中没有开始AUTH_MODE_CERT
2.编译无法正常通过，提示缺少一些DTLS相关 API定义。我直接屏蔽了，应为并没有使用。
3.TLS同云端握手失败，好像需要在sdk 配置TLS认证方式，具体也没有进行探究，我几乎开启了所有的tls协商方式，就可以正常握手了
NOTE
我使用的是esp8266，sdk为tag 3.1

**Comment by Jiangwei0802** [comment]
你这几个问题都解了吗？

**Comment by jsonsiyuan** [comment]
yes， 不过是取巧的解决了问题，为了解决问题而解决问题

**Comment by Jiangwei0802** [comment]
我这边在pc上用mqtt.fx软件用证书方式和key方式连接是没问题的；看SDK里面不是用的证书方式，我用key连接的时候总是认证报错，跟你确认下mqtt初始化信息里面那个device_secret对应的是后台的product_secret呢还是设备列表里面对应设备的密钥

**Comment by jsonsiyuan** [comment]
认证报错其实是TLS同云端握手失败，需要在sdk 配置TLS认证方式，具体也没有进行探究，我几乎开启了所有的tls协商方式，就可以正常握手了

**Comment by jsonsiyuan** [comment]
关于第三点的加密问题，我已经研究完成，需要开启  Enable PSK based ciphersuite modes
