### ISSUE TITLE
SDK的问题

### ISSUE THREAD

**Issue by Jiangwei0802** [espressif/esp-qcloud#5]
1.编译不通过：提示缺少一些DTLS相关 API定义
![image](https://user-images.githubusercontent.com/9602379/71791009-5511ff00-306e-11ea-9186-0cfdfa48d81c.png)

2.文档与实际SDK里面设置不符合
这个demo的readme说明有勘误，这是一个没有使用证书认证的demo，而是使用了设备密钥认证的demo。代码中没有开始AUTH_MODE_CERT

3.TLS握手失败

4.腾讯云的几种认证方式目前是否   证书认证、密钥认证、动态认证都支持？

**Comment by jsonsiyuan** [comment]
对于TLS握手失败 需要开启 密钥协商中的 Enable PSK based ciphersuite modes

**Comment by songjiaxiu-espressif** [comment]
@Jiangwei0802 
     您好。
1. 编译不通过：提示缺少一些DTLS相关 API定义
                  -----------------------------------------------
要在 `make menuconfig` -> `Component config` -> `mbedTLS` -> `support DTLS protocol` 选中，如下图所示：

![image](https://user-images.githubusercontent.com/54977525/72124208-d931f280-339e-11ea-8a10-40d8fe2557b7.png)

2. 文档与实际SDK里面设置不符合
               ---------------------------------------------------
文档目前还没有更新，这个 `demo`, 对于证书方式和设备认证方式都是支持的，其中 `AUTH_MODE_CERT` 定义分别针对 `cmake` 和 `make` 的编译方式，在目录下 `CMakLists.txt`,`component.mk` 文件中选择是否定义.

3.TLS握手失败
            ------------------------------------------------------
同样在 `make menuconfig` 中 Component config > mbedTLS > TLS Key Exchange Methods 中设置 `Enable pre-shared-key ciphersuites` 选中，如下图所示：

![image](https://user-images.githubusercontent.com/54977525/72124828-18f9d980-33a1-11ea-9e3b-cd909cbcb053.png)

4. 目前支持证书认证、密钥认证

针对1和3问题，`demo` 下的 `sdkconfig.defaults` 中做了默认配置。

**Comment by wenkumk** [comment]
> @Jiangwei0802
> 您好。
> 
> 1. 编译不通过：提示缺少一些DTLS相关 API定义
>    -----------------------------------------------
>    要在 `make menuconfig` -> `Component config` -> `mbedTLS` -> `support DTLS protocol` 选中，如下图所示：
> 
> ![image](https://user-images.githubusercontent.com/54977525/72124208-d931f280-339e-11ea-8a10-40d8fe2557b7.png)
> 
> 1. 文档与实际SDK里面设置不符合
>    ---------------------------------------------------
>    文档目前还没有更新，这个 `demo`, 对于证书方式和设备认证方式都是支持的，其中 `AUTH_MODE_CERT` 定义分别针对 `cmake` 和 `make` 的编译方式，在目录下 `CMakLists.txt`,`component.mk` 文件中选择是否定义.
> 
> 3.TLS握手失败
> ------------------------------------------------------
> 同样在 `make menuconfig` 中 Component config > mbedTLS > TLS Key Exchange Methods 中设置 `Enable pre-shared-key ciphersuites` 选中，如下图所示：
> 
> ![image](https://user-images.githubusercontent.com/54977525/72124828-18f9d980-33a1-11ea-9e3b-cd909cbcb053.png)
> 
> 1. 目前支持证书认证、密钥认证
> 
> 针对1和3问题，`demo` 下的 `sdkconfig.defaults` 中做了默认配置。

![1582185695(1)](https://user-images.githubusercontent.com/35908729/74913586-ee695a80-53fb-11ea-8449-a3160e548e77.jpg)
编译后现在有这几个报错是什么愿意呢

**Comment by xiewenxiang** [comment]
如果还有问题，可以重新打开这个issues
