### ISSUE TITLE
编译遇到如下问题

### ISSUE THREAD

**Issue by wenkumk** [espressif/esp-qcloud#7]
![1579224167(1)](https://user-images.githubusercontent.com/35908729/72576631-37b12080-390b-11ea-9022-4d5838286f9f.jpg)
![1579224214(1)](https://user-images.githubusercontent.com/35908729/72576632-37b12080-390b-11ea-9d2a-00d8e14fe569.jpg)
![1579224236(1)](https://user-images.githubusercontent.com/35908729/72576633-3849b700-390b-11ea-8d06-6346262c9779.jpg)
![1579224255(1)](https://user-images.githubusercontent.com/35908729/72576634-3849b700-390b-11ea-81a6-4771de4a8848.jpg)

**Comment by songjiaxiu-espressif** [comment]
这个问题详见: https://github.com/espressif/esp-qcloud/issues/5

**Comment by wenkumk** [comment]
>

> 这个问题详见: #5

![1579225833(1)](https://user-images.githubusercontent.com/35908729/72577789-ee62d000-390e-11ea-8886-675b81f5a1d0.jpg)


按照那个来现在编译是这个结果

**Comment by songjiaxiu-espressif** [comment]
先清一下编译环境---
----`make clean`
----rm build/  -rf
----rm sdkconfig sdkconfig.old
然后，重新在make menuconfig 中配置，编译
如果还有问题的话，请提供一下 IDF 的版本和commit

**Comment by wenkumk** [comment]
> 先清一下编译环境---
> ----`make clean`
> ----rm build/ -rf
> ----rm sdkconfig sdkconfig.old
> 然后，重新在make menuconfig 中配置，编译
> 如果还有问题的话，请提供一下 IDF 的版本和commit

IDF的版本哪里看呢，我用的是git clone -b v3.1 这样去下载的。
![1579239119(1)](https://user-images.githubusercontent.com/35908729/72586741-d2225b80-392d-11ea-9a23-f2218f1e6cd2.jpg)

**Comment by songjiaxiu-espressif** [comment]
@wenkumk 可以在`IDF` 下用 `git` 命令查看，现在在8266 `v3.3-rc1` tag 的分支上支持 `qcloud`

**Comment by wenkumk** [comment]
> @wenkumk可以在`IDF`下用`git`命令查看，现在在8266`v3.3-rc1`标签的分支上支持`qcloud`

![1582185695(1)](https://user-images.githubusercontent.com/35908729/74913437-992d4900-53fb-11ea-9ad9-5befbac68ce2.jpg)
编译下载后这个报错是怎么解决呢
